#!/bin/bash
echo -n "Supervisor " && supervisord --version
git --version
zsh --version

php --version
composer --version
phpunit --version
drush --version
hhvm --version

echo -n "Node " && node --version
echo -n "npm " && npm --version
echo -n "iojs " && iojs --version

python --version
python3 --version

ruby2.1 --version
echo -n "Gem version:" && gem --version
bundle --version
rake --version
sass --version
compass --version

go version

rustc --version
cargo --version
